[package]
name = "tink-awskms"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
csv = "^1.1.3"
hex = "^0.4.2"
regex = "^1.4.2"
rusoto_core = "^0.45"
rusoto_credential = "^0.45"
rusoto_kms = "^0.45"
tink = "^0.1"
# Match the version of tokio required by rusoto_* v0.45.0
tokio = "^0.2.22"

[dev-dependencies]
tink-aead = "^0.1"
tink-testutil = "^0.1"
