[package]
name = "tink-mac"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
prost = "^0.6.1"
tink = "^0.1"
tink-prf = "^0.1"

[dev-dependencies]
base64 = "^0.12"
hex = "^0.4.2"
lazy_static = "^1.4"
maplit = "^1.0.2"
serde = { version = "^1.0.116", features = ["derive"] }
serde_json = "^1.0.60"
tink-prf = "^0.1"
tink-testutil = "^0.1"
