[package]
name = "tink-daead"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
aead = { version = "^0.3.2", features = ["std"] }
aes-siv = "^0.5"
prost = "^0.6.1"
tink = "^0.1"

[dev-dependencies]
base64 = "^0.12"
hex = "^0.4.2"
serde = { version = "^1.0.118", features = ["derive"] }
serde_json = "^1.0.60"
tink-signature = "^0.1"
tink-testutil = "^0.1"
