[package]
name = "rinkey"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[dependencies]
structopt = "*"
tink = { version = "*", features = ["insecure"] }
tink-aead = "*"
tink-awskms = "*"
tink-daead = "*"
tink-mac = "*"
tink-prf = "*"
tink-signature = "*"
