[package]
name = "example-streaming"
version = "0.2.3"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[dependencies]
tempfile = "^3.4"
tink-core = "^0.2"
tink-streaming-aead = "^0.2"
